// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blogChatRecord.proto

package protoCompiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlogChatRecord struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Room                 string   `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogChatRecord) Reset()         { *m = BlogChatRecord{} }
func (m *BlogChatRecord) String() string { return proto.CompactTextString(m) }
func (*BlogChatRecord) ProtoMessage()    {}
func (*BlogChatRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae840149edb11386, []int{0}
}

func (m *BlogChatRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogChatRecord.Unmarshal(m, b)
}
func (m *BlogChatRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogChatRecord.Marshal(b, m, deterministic)
}
func (m *BlogChatRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogChatRecord.Merge(m, src)
}
func (m *BlogChatRecord) XXX_Size() int {
	return xxx_messageInfo_BlogChatRecord.Size(m)
}
func (m *BlogChatRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogChatRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BlogChatRecord proto.InternalMessageInfo

func (m *BlogChatRecord) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogChatRecord) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *BlogChatRecord) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BlogChatRecord) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *BlogChatRecord) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*BlogChatRecord)(nil), "blog_chat_record")
}

func init() { proto.RegisterFile("blogChatRecord.proto", fileDescriptor_ae840149edb11386) }

var fileDescriptor_ae840149edb11386 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x3d, 0x0e, 0x82, 0x40,
	0x10, 0x46, 0xb3, 0x08, 0x1a, 0xc7, 0xf8, 0x93, 0x8d, 0xc5, 0x76, 0x12, 0x2b, 0x2a, 0x1b, 0x6f,
	0x20, 0x37, 0x20, 0x56, 0x36, 0x04, 0x76, 0x27, 0xb2, 0x09, 0xcb, 0x90, 0x75, 0xbc, 0x88, 0x27,
	0x36, 0x0c, 0xd1, 0x6e, 0xbe, 0xf7, 0x5e, 0x31, 0x70, 0x6c, 0x7b, 0x7a, 0x96, 0x5d, 0xc3, 0x15,
	0x5a, 0x8a, 0xee, 0x32, 0x46, 0x62, 0x3a, 0x7f, 0x14, 0x1c, 0x26, 0x51, 0xdb, 0xae, 0xe1, 0x3a,
	0x8a, 0xd2, 0x3b, 0x48, 0xbc, 0x33, 0x2a, 0x57, 0x45, 0x56, 0x25, 0xde, 0x69, 0x0d, 0x69, 0x24,
	0x0a, 0x26, 0xc9, 0x55, 0xb1, 0xae, 0xe4, 0xd6, 0x06, 0x56, 0x96, 0x06, 0xc6, 0x81, 0xcd, 0x42,
	0xf0, 0x6f, 0xea, 0x13, 0x6c, 0x6c, 0xc4, 0x86, 0xb1, 0x66, 0x1f, 0xd0, 0xa4, 0x62, 0x61, 0x46,
	0x77, 0x1f, 0x70, 0x0a, 0xde, 0xa3, 0xfb, 0x07, 0xd9, 0x1c, 0xcc, 0x68, 0x0a, 0x6e, 0xfb, 0xc7,
	0x56, 0xbe, 0x2b, 0x29, 0x8c, 0xbe, 0xc7, 0x57, 0xbb, 0x94, 0x79, 0xfd, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x8e, 0x1e, 0xc3, 0x79, 0xc4, 0x00, 0x00, 0x00,
}
