// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blogType.proto

package protoCompiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlogType struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogNum              int32    `protobuf:"varint,2,opt,name=blog_num,json=blogNum,proto3" json:"blog_num,omitempty"`
	Lable                string   `protobuf:"bytes,3,opt,name=lable,proto3" json:"lable,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogType) Reset()         { *m = BlogType{} }
func (m *BlogType) String() string { return proto.CompactTextString(m) }
func (*BlogType) ProtoMessage()    {}
func (*BlogType) Descriptor() ([]byte, []int) {
	return fileDescriptor_3072e1a56ecc200b, []int{0}
}

func (m *BlogType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogType.Unmarshal(m, b)
}
func (m *BlogType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogType.Marshal(b, m, deterministic)
}
func (m *BlogType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogType.Merge(m, src)
}
func (m *BlogType) XXX_Size() int {
	return xxx_messageInfo_BlogType.Size(m)
}
func (m *BlogType) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogType.DiscardUnknown(m)
}

var xxx_messageInfo_BlogType proto.InternalMessageInfo

func (m *BlogType) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogType) GetBlogNum() int32 {
	if m != nil {
		return m.BlogNum
	}
	return 0
}

func (m *BlogType) GetLable() string {
	if m != nil {
		return m.Lable
	}
	return ""
}

func (m *BlogType) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *BlogType) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*BlogType)(nil), "blog_type")
}

func init() { proto.RegisterFile("blogType.proto", fileDescriptor_3072e1a56ecc200b) }

var fileDescriptor_3072e1a56ecc200b = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xca, 0xc9, 0x4f,
	0x0f, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xea, 0x63, 0xe4, 0xe2, 0x04,
	0x09, 0xc5, 0x97, 0x54, 0x16, 0xa4, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x49, 0x72, 0x71, 0x80, 0x25, 0xf3, 0x4a, 0x73, 0x25,
	0x98, 0xc0, 0xa2, 0xec, 0x20, 0xbe, 0x5f, 0x69, 0xae, 0x90, 0x08, 0x17, 0x6b, 0x4e, 0x62, 0x52,
	0x4e, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0x23, 0x24, 0xcf, 0xc5, 0x9d, 0x5c,
	0x94, 0x9a, 0x58, 0x92, 0x1a, 0x5f, 0x92, 0x99, 0x9b, 0x2a, 0xc1, 0x02, 0x96, 0xe3, 0x82, 0x08,
	0x85, 0x64, 0xe6, 0x82, 0x15, 0x94, 0x16, 0xa4, 0xc0, 0x15, 0xb0, 0x42, 0x14, 0x40, 0x84, 0x40,
	0x0a, 0x9c, 0xf8, 0xa3, 0x78, 0xc1, 0x2e, 0x73, 0xce, 0xcf, 0x2d, 0xc8, 0xcc, 0x49, 0x2d, 0x4e,
	0x62, 0x03, 0x73, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x18, 0x45, 0xcc, 0xba, 0x00,
	0x00, 0x00,
}
