// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blogView.proto

package protoCompiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlogView struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Isp                  string   `protobuf:"bytes,5,opt,name=isp,proto3" json:"isp,omitempty"`
	BlogId               int32    `protobuf:"varint,6,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Ip                   string   `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogView) Reset()         { *m = BlogView{} }
func (m *BlogView) String() string { return proto.CompactTextString(m) }
func (*BlogView) ProtoMessage()    {}
func (*BlogView) Descriptor() ([]byte, []int) {
	return fileDescriptor_3846c45f28eac7f7, []int{0}
}

func (m *BlogView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogView.Unmarshal(m, b)
}
func (m *BlogView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogView.Marshal(b, m, deterministic)
}
func (m *BlogView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogView.Merge(m, src)
}
func (m *BlogView) XXX_Size() int {
	return xxx_messageInfo_BlogView.Size(m)
}
func (m *BlogView) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogView.DiscardUnknown(m)
}

var xxx_messageInfo_BlogView proto.InternalMessageInfo

func (m *BlogView) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogView) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *BlogView) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *BlogView) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *BlogView) GetIsp() string {
	if m != nil {
		return m.Isp
	}
	return ""
}

func (m *BlogView) GetBlogId() int32 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *BlogView) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BlogView) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *BlogView) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*BlogView)(nil), "blog_view")
}

func init() { proto.RegisterFile("blogView.proto", fileDescriptor_3846c45f28eac7f7) }

var fileDescriptor_3846c45f28eac7f7 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x40, 0x65, 0xb7, 0x75, 0xc8, 0x21, 0x0a, 0xba, 0x01, 0x6e, 0xa3, 0x62, 0xea, 0xc4, 0xc2,
	0x1f, 0xc0, 0xc4, 0x5a, 0x21, 0x06, 0x96, 0x8a, 0xc6, 0xa7, 0xea, 0xa4, 0x24, 0xb6, 0x1c, 0x87,
	0x28, 0x3f, 0xcb, 0xb7, 0x20, 0x5f, 0x80, 0xed, 0xde, 0xbb, 0x27, 0x9d, 0x0d, 0xdb, 0x53, 0x1b,
	0xce, 0xef, 0xc2, 0xd3, 0x63, 0x4c, 0x21, 0x87, 0x87, 0x6f, 0x03, 0x75, 0x51, 0xc7, 0x2f, 0xe1,
	0x09, 0xb7, 0x60, 0xc5, 0x93, 0xd9, 0x99, 0xfd, 0xe6, 0x60, 0xc5, 0x23, 0x41, 0xd5, 0x84, 0xb1,
	0xcf, 0x69, 0x26, 0xbb, 0x33, 0xfb, 0xfa, 0xf0, 0x87, 0x78, 0x0b, 0x2e, 0xf1, 0x59, 0x42, 0x4f,
	0x2b, 0x5d, 0xfc, 0x12, 0x22, 0xac, 0x1b, 0xc9, 0x33, 0xad, 0xd5, 0xea, 0x8c, 0x37, 0xb0, 0x92,
	0x21, 0xd2, 0x46, 0x55, 0x19, 0xf1, 0x0e, 0x2a, 0x3d, 0x2a, 0x9e, 0x9c, 0x1e, 0x73, 0x05, 0x5f,
	0xbd, 0x3e, 0x20, 0x52, 0xa5, 0xa5, 0x95, 0x88, 0xf7, 0x70, 0xd9, 0x24, 0xfe, 0xcc, 0x7c, 0xcc,
	0xd2, 0x31, 0x5d, 0xe8, 0x02, 0x16, 0xf5, 0x26, 0x1d, 0x97, 0x60, 0x8c, 0xfe, 0x3f, 0xa8, 0x97,
	0x60, 0x51, 0x25, 0x78, 0xbe, 0xfe, 0xb8, 0xd2, 0x9f, 0xbe, 0x84, 0x2e, 0x4a, 0xcb, 0xc3, 0xc9,
	0x29, 0x3e, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x0c, 0x27, 0x06, 0x0a, 0x01, 0x00, 0x00,
}
