// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors.proto

package protoCompiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCodes int32

const (
	ErrorCodes_F              ErrorCodes = 0
	ErrorCodes_OK             ErrorCodes = 200
	ErrorCodes_NOCONTENT      ErrorCodes = 204
	ErrorCodes_INVALID_PARAMS ErrorCodes = 400
	ErrorCodes_UNAUTHORIZED   ErrorCodes = 401
	ErrorCodes_FORBIDDEN      ErrorCodes = 403
	ErrorCodes_NOTFOUND       ErrorCodes = 404
	ErrorCodes_ERROR          ErrorCodes = 500
)

var ErrorCodes_name = map[int32]string{
	0:   "F",
	200: "OK",
	204: "NOCONTENT",
	400: "INVALID_PARAMS",
	401: "UNAUTHORIZED",
	403: "FORBIDDEN",
	404: "NOTFOUND",
	500: "ERROR",
}

var ErrorCodes_value = map[string]int32{
	"F":              0,
	"OK":             200,
	"NOCONTENT":      204,
	"INVALID_PARAMS": 400,
	"UNAUTHORIZED":   401,
	"FORBIDDEN":      403,
	"NOTFOUND":       404,
	"ERROR":          500,
}

func (x ErrorCodes) String() string {
	return proto.EnumName(ErrorCodes_name, int32(x))
}

func (ErrorCodes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24fe73c7f0ddb19c, []int{0}
}

type Resp struct {
	Code                 ErrorCodes `protobuf:"varint,1,opt,name=code,proto3,enum=ErrorCodes" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_24fe73c7f0ddb19c, []int{0}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() ErrorCodes {
	if m != nil {
		return m.Code
	}
	return ErrorCodes_F
}

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("ErrorCodes", ErrorCodes_name, ErrorCodes_value)
	proto.RegisterType((*Resp)(nil), "resp")
}

func init() { proto.RegisterFile("errors.proto", fileDescriptor_24fe73c7f0ddb19c) }

var fileDescriptor_24fe73c7f0ddb19c = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2d, 0x2a, 0xca,
	0x2f, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe2, 0x62, 0x29, 0x4a, 0x2d, 0x2e,
	0x10, 0x52, 0xe0, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0xe2,
	0xd1, 0x03, 0x2b, 0x8a, 0x07, 0x09, 0x15, 0x07, 0x81, 0x65, 0x84, 0x04, 0xb8, 0x98, 0x73, 0x8b,
	0xd3, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0xad, 0x06, 0x46, 0x2e, 0x6e, 0x24,
	0x75, 0x42, 0xac, 0x5c, 0x8c, 0x6e, 0x02, 0x0c, 0x42, 0xec, 0x5c, 0x4c, 0xfe, 0xde, 0x02, 0x27,
	0x18, 0x85, 0xf8, 0xb8, 0x38, 0xfd, 0xfc, 0x9d, 0xfd, 0xfd, 0x42, 0x5c, 0xfd, 0x42, 0x04, 0xce,
	0x30, 0x0a, 0x09, 0x73, 0xf1, 0x79, 0xfa, 0x85, 0x39, 0xfa, 0x78, 0xba, 0xc4, 0x07, 0x38, 0x06,
	0x39, 0xfa, 0x06, 0x0b, 0x4c, 0x60, 0x16, 0x12, 0xe4, 0xe2, 0x09, 0xf5, 0x73, 0x0c, 0x0d, 0xf1,
	0xf0, 0x0f, 0xf2, 0x8c, 0x72, 0x75, 0x11, 0x98, 0xc8, 0x0c, 0xd2, 0xe7, 0xe6, 0x1f, 0xe4, 0xe4,
	0xe9, 0xe2, 0xe2, 0xea, 0x27, 0x30, 0x99, 0x59, 0x88, 0x97, 0x8b, 0xc3, 0xcf, 0x3f, 0xc4, 0xcd,
	0x3f, 0xd4, 0xcf, 0x45, 0x60, 0x0a, 0xb3, 0x10, 0x17, 0x17, 0xab, 0x6b, 0x50, 0x90, 0x7f, 0x90,
	0xc0, 0x17, 0x66, 0x27, 0xfe, 0x28, 0x5e, 0xb0, 0x3f, 0x9c, 0xf3, 0x73, 0x0b, 0x32, 0x73, 0x52,
	0x8b, 0x93, 0xd8, 0xc0, 0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x52, 0xba, 0x5d,
	0xe6, 0x00, 0x00, 0x00,
}
