runmode: release
grpc:
  port: 14100
http:
  port: 14001
mysql:
  master:
    addr: root:930218hX@tcp(140.143.188.219:3306)/tr?charset=utf8mb4&parseTime=True&loc=Local
    maxOpenConns: 100
    maxIdleConns: 5
redis:
  host: 127.0.0.1
  password:
  port: 6379
